#Variables
@baseUrl = http://localhost:3333

#Health check
GET {{baseUrl}}/health

###

#Get rooms
GET {{baseUrl}}/rooms

###

#Get rooms questions
GET {{baseUrl}}/rooms/0dbc2f98-4968-44be-4fdb-f399737e5e21/questions


###

#Create room
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "sala",
    "description": "teste"
}

###

#Create question
POST {{baseUrl}}/rooms/0dbc2f98-4968-44be-4fdb-f399737e5e21/questions
Content-Type: application/json

{
    "question": "What is a question?"
}